### ISSUE TITLE
How to add this to existing Model with Records?

### ISSUE THREAD

**Issue by stripathi669** [mkrjhnsn/django-randomslugfield#3]
How can I add this field to existing model with existing records and still fill the random-slugfield?

**Comment by mkrjhnsn** [comment]
It isn't possible to fill the slug field on existing models.
If you manually create slugs for all preexisting records the field will prevent new slugs it generates from conflicting.

**Comment by mkrjhnsn** [comment]
The best way to do what you want would be to do a data migration.
https://docs.djangoproject.com/en/dev/topics/migrations/#data-migrations
